### ISSUE TITLE
OpenAPI 3 support

### ISSUE THREAD

**Issue by kojidev** [GuilhemN/swagger#8]
Hi, repo seems pretty straightforward, make a class one-by-one to spec objects, but so much time and still no OAS3 :(
Should we keep Swagger 2.0 support (if so how do we structure classes, they are different)
P.S. I'd love to contribute

**Comment by GuilhemN** [comment]
> Should we keep Swagger 2.0 support (if so how do we structure classes, they are different)

I don't think this is needed, we can maintain one version of the library for 2.0 and one for 3.0. So I'd say we keep the same structure and we just adapt it to 3.0. I can create a dev branch to do it step by step (create new classes, update old ones etc.).

I would greatly appreciate some help on this one, I won't be able to spend much time on this unfortunately...

**Comment by kojiDev** [comment]
@GuilhemN bet

**Comment by kojiDev** [comment]
Create a branch please :)

**Comment by GuilhemN** [comment]
Done :) (I created the dev branch)

**Comment by GuilhemN** [comment]
We would need a dedicated `validate` method for this imo. It would be a nice addition but I think we should advance step by step and first work on 3.0 support :)

**Comment by kojiDev** [comment]
@GuilhemN 
Yeah, I see. I've made first green OAS3 Test: https://github.com/kojiDev/swagger/commit/d106af60e7cc980ab3f094954d3192ab1709f0c0
It's mess for now, and I added as small code as possible to make test green, I just wanted to make sure that it is doable to maintain 2 and 3 versions together.

And even though it IS doable it's painful :) Especially if we want to make it fail fast. (Validate method that is going to be invoked afterward leaves the graph invalid until we check). And I'm not sure how we will validate it since requirements for same Objects are different in both specs.

People will need to read OAS3 Spec very carefully to not mistakenly put Swagger2's property into shared, say Parameter Object.

Are you sure you don't want to drop 2? Or support multiple versions instead of fuse them into one class base? I'm saying this because I'm pretty sure it will slows down the development process.

**Comment by GuilhemN** [comment]
Sorry I wasn't clear, I meant supporting 2.0 and 3.0 on different branches, I'm fine with removing 2.0 support in the dev branch.

> Yeah, I see. I've made first green OAS3 Test: 

Looks promising :)

**Comment by kojiDev** [comment]
@GuilhemN Oh, that's cool

**Comment by kojiDev** [comment]
@GuilhemN 

Ok, I made [this 6 OAS3 examples](https://github.com/OAI/OpenAPI-Specification/tree/1bd512e358bf92c841002011493d7d7daa7b85d4/examples/v3.0) green.

It's mess for now (no getters/setters, validation), but it works
Next thing we probably need to do is to write detailed Unit tests for every Spec Object, including setters/getter/adders and validation. But before I'd like to ask you to review what I wrote here and code itself :) https://github.com/GuilhemN/swagger/compare/dev...kojiDev:dev?expand=1

## Things that I've done on the way and we might want to discuss:

### 1. Changed namespace from `EXSyst\Component\Swagger` to `EXSyst\OAS`
 - `Component` because it doesn't represent actual content of the folder
 - `Swagger` to `OAS` obviously

### 2. Removed merge/doMerge methods in favor of just configuring everything in constructor:
```
final class Contact extends AbstractObject
{
    public function __construct(array $data = [])
    {
        $this->name = $data['name'] ?? null;
        $this->url = $data['url'] ?? null;
        $this->email = $data['email'] ?? null;

        $this->mergeExtensions($data);
    }
    //...
}
```
that way we can fail faster

### 3. Removed all `*Part` traits except `ExtensionPart`
And declared all these fields/getters/setters in classes themselves, because sometimes those same named fields are treated differently (getters/setters might be nullable or not etc.). Extensible fields are always populated and exported the same way so I left it.

### 4. Made things simpler but longer and duller
I'm not big fan of copy/pasting but sometimes I think it's better to write more code that is simpler and more explicit.
Header Before:
```
public function doMerge($data = [])
{
    $this->mergeDescription($data, $overwrite);
    $this->mergeExtensions($data, $overwrite);
    $this->mergeItems($data, $overwrite);
    $this->mergeType($data, $overwrite);
}

public function doExport(): array
{
    return array_merge(
        [
            'description' => $this->description,
            'items' => $this->items,
        ],
        $this->doExportType()
    );
}
```
Header After
```
public function __construct(array $data)
{
    $this->description = $data['description'] ?? null;
    $this->schema = isset($data['schema']) ? referenceOr(Schema::class, $data['schema']) : null;
    $this->mergeExtensions($data);
}

public function export(): array
{
    $return = [
        'schema' => $this->schema,
    ];

    if ($this->description) {
        $return['description'] = $this->description;
    }

    return $return;
}
```

The reasoning behind this is that instantiating/exporting could vary from property to property and it's too difficult to write a function that will handle all scenarios. Sometimes you need null properties to be exported, sometimes not, the same about empty collections/objects, so I figured out that it's better to leave this processes for Object itself to handle

### 5. Reference is Object now

### 6. Collection folder now contains only helper collections that are necessary to work, but don't exist in actual spec.


P.S. I might forgot to mention something.
P.P.S. I forgot that it is OSS and I'm not the only person who can play with dev branch, I didn't notice that you were committing to dev to, so there will be conflicts, I'll fix them.

**Comment by GuilhemN** [comment]
> Changed namespace from EXSyst\Component\Swagger to EXSyst\OAS

I'd rather use `OAI` since it's the name of the open api organisation (https://github.com/OAI). (And OAS is not neutral regarding history 😅)

> Removed merge/doMerge methods 

These methods are very useful in https://github.com/nelmio/NelmioApiDocBundle but I guess they're bad practice so if you think we should remove them, let's do it :+1:

> But before I'd like to ask you to review what I wrote here and code itself :) https://github.com/GuilhemN/swagger/compare/dev...kojiDev:dev?expand=1 

Could you open a PR to allow me to let comments please ?

Looking at the diff, you've done an incredible job, the lib looks better than it does right now 😮
Thanks a lot :)

> P.P.S. I forgot that it is OSS and I'm not the only person who can play with dev branch, I didn't notice that you were committing to dev to, so there will be conflicts, I'll fix them. 

No problem, I duplicated some of your changes, I will just revert them :)

**Comment by kojiDev** [comment]
@GuilhemN 

> Could you open a PR to allow me to let comments please ?

done.
Comment it and then I will continue.

OAI is organization's name, hmm mb just **OpenAPI** then)

> These methods are very useful in https://github.com/nelmio/NelmioApiDocBundle but I guess they're bad practice so if you think we should remove them, let's do it 👍

I checked the usage of `merge` in nelmio's bundle, it will not be a problem there will be proper methods for it, bc will be broke ofc, but it's necessary due to difference in specs

**Comment by kojiDev** [comment]
@GuilhemN 
Hi, I've been busy for last month, but now I feel like I can dedicate some time.
There's a think that bothers me, I personally use $refs a lot, it's handy when you don't want duplicate schemes, for example I have schema like this:

id.json
```
{
  "type": "string",
  "format": "uuid",
  "example": "1ba0fae4-d512-4e89-b916-106dac3d77f2"
}
```

and I reference it everywhere.

In JSON I'm free to reference whatever I want, and I don't want to loose this opportunity using this lib.

But it means that practically every setter should not have a type-hint and should have assertion inside, like:
`assertReferenceOr(Operation::class, $data)` or `assertReferenceOr('string', $data)`
I can write doc blocks like tho
```
/**
 * @param Operation|Reference $data
 */
```

What you think?

**Comment by kojiDev** [comment]
@GuilhemN What behavior should be when I pass non existing fields to an Object?
for example:
```PHP
new OpenApi([
    'info' => [
        'version' => '1.0.0',
        'title' => 'Title',
    ],
    'whatever' => true,
]);
```

I now having headache when I try to feed my OpenApi yaml/json payloads to the Object, it swallows it and if I have errors like:

```YAML
allOf:
- $ref: 'SomeSchema.yaml'
- anotherField: #forgot properties:
      type: array
        items:
          type: string
```

it just ignores that.

**Comment by GuilhemN** [comment]
NelmioApiDocBundle now supports OpenApi 3.0! See https://github.com/nelmio/NelmioApiDocBundle/pull/1623 :)
I'm closing this issue as I don't think it's truly needed anymore, thanks!
